// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btsatlgulgebxxijfamp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0c2F0bGd1bGdlYnh4aWpmYW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDc2MDgsImV4cCI6MjA2MzUyMzYwOH0.d0Gs3f-BDvXJHUmmofUB7WL5jsJNUEOomJ0gs-xq2-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);